"""Detecting drift in Claude Code's own env block.

The env-block field templates survive in the installed binary's string table
as plain literals. Reading the installed binary rather than a decompiled dump
is what makes the check track upgrades on its own: the dump is regenerated by
hand, the binary changes underfoot.

The check sees labels only. A change to how cc computes a value without
changing its label will not trip it, which is why the manifest pins the cc
version alongside the literals.
"""

from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
from collections.abc import Callable, Mapping
from dataclasses import dataclass, field
from pathlib import Path
from typing import TypedDict, cast

ANCHOR = b"You have been invoked in the following environment: "
WINDOW_BEFORE = 3000
WINDOW_AFTER = 1500
PRINTABLE = re.compile(rb"[\x20-\x7e]{12,}")


class ManifestData(TypedDict):
    """The pinned-manifest shape `compare()` reads.

    basedpyright cannot check value types coming from json.loads, which are
    Any regardless of this declaration -- see `Facts` in render.py for the
    same caveat. The win here is the key set: a typo'd or renamed manifest
    key fails at the subscript instead of silently reading as Any everywhere
    downstream.
    """

    version: str
    window_literals: list[str]
    required_literals: dict[str, int]


class CacheEntry(TypedDict):
    """The on-disk shape of the drift cache file `cached_note()` reads back."""

    binary: str
    size: int
    mtime_ns: int
    note: str | None


@dataclass
class Comparison:
    matches: bool
    installed_version: str
    pinned_version: str
    added: list[str] = field(default_factory=list)
    removed: list[str] = field(default_factory=list)
    count_changes: dict[str, tuple[int, int]] = field(default_factory=dict)


def find_binary(env: Mapping[str, str] | None = None) -> Path:
    """Locate the running Claude Code binary.

    CLAUDE_CODE_EXECPATH is set in hook and tool subprocess environments and
    names the binary directly. The PATH fallback lands on a wrapper script
    under Nix, whose sibling `.claude-wrapped` symlink points at the real one.
    """
    env = os.environ if env is None else env
    execpath = env.get("CLAUDE_CODE_EXECPATH")
    if execpath and Path(execpath).is_file():
        return Path(execpath)

    found = shutil.which("claude", path=env.get("PATH"))
    if not found:
        raise RuntimeError("claude is not on PATH and CLAUDE_CODE_EXECPATH is unset")
    real = Path(os.path.realpath(found))
    if ANCHOR in real.read_bytes():
        return real
    wrapped = real.parent / ".claude-wrapped"
    if wrapped.exists():
        return Path(os.path.realpath(wrapped))
    raise RuntimeError(
        f"{real} carries no env-block anchor and has no .claude-wrapped sibling"
    )


def literals_in(data: bytes, source: str) -> list[str]:
    index = data.find(ANCHOR)
    if index < 0:
        raise RuntimeError(f"env-block anchor not found in {source}")
    window = data[max(0, index - WINDOW_BEFORE) : index + WINDOW_AFTER]
    # PRINTABLE has no capture groups, so every match is the full bytes
    # object; findall()'s return type is `list[Any]` in typeshed regardless
    # (it has to accommodate patterns that do have groups), hence the cast.
    matches = cast(list[bytes], PRINTABLE.findall(window))
    return sorted({m.decode() for m in matches})


def extract_literals(binary: Path) -> list[str]:
    return literals_in(binary.read_bytes(), str(binary))


def installed_version() -> str:
    result = subprocess.run(["claude", "--version"], capture_output=True, text=True)
    if result.returncode != 0:
        raise RuntimeError(f"claude --version failed: {result.stderr.strip()}")
    return result.stdout.split()[0]


def compare(binary: Path, manifest: Path, version: str) -> Comparison:
    """Diff the installed binary against the pinned manifest.

    The binary is 331 MB, so it is read once and both checks run over the same
    bytes. `window_literals` catches fields cc adds near the anchor.
    `required_literals` catches a rename or removal of templates the
    window cannot see: one under its 12-character floor, one too far from the
    anchor, or one carrying a non-ASCII character, which the string table holds
    as UTF-16 where the ASCII-only regex misses it even inside the window.
    These are compared by occurrence count rather than presence, because the
    strings also occur elsewhere in the binary — a rename scoped to cc's env
    builders leaves them present while dropping the total. See
    `notes/env-context-manifest.md`.
    """
    pinned = cast(ManifestData, json.loads(manifest.read_text()))
    data = binary.read_bytes()
    found = set(literals_in(data, str(binary)))
    expected = set(pinned["window_literals"])
    added = sorted(found - expected)
    removed = sorted(expected - found)
    changed = {
        literal: (pinned_count, data.count(literal.encode()))
        for literal, pinned_count in pinned["required_literals"].items()
        if pinned_count != data.count(literal.encode())
    }
    return Comparison(
        matches=(
            not added
            and not removed
            and not changed
            and version == pinned["version"]
        ),
        installed_version=version,
        pinned_version=pinned["version"],
        added=added,
        removed=removed,
        count_changes=changed,
    )


def cached_note(
    binary: Path,
    manifest: Path,
    cache: Path,
    version: Callable[[], str] = installed_version,
) -> str | None:
    """Return a one-line drift note, or None when the field set still matches.

    The result is cached on the binary's size and mtime, so the full scan runs
    once per Claude Code upgrade rather than once per session.
    """
    stat = binary.stat()
    key = {"binary": str(binary), "size": stat.st_size, "mtime_ns": stat.st_mtime_ns}

    if cache.is_file():
        stored = cast(CacheEntry, json.loads(cache.read_text()))
        if all(stored.get(k) == v for k, v in key.items()):
            return stored.get("note")

    result = compare(binary, manifest, version())
    note = None
    if not result.matches:
        note = (
            f"Claude Code {result.installed_version} changed its env block since the "
            f"{result.pinned_version} field set this hook is pinned to. Run "
            "scripts/check-env-context.sh to review."
        )
    cache.parent.mkdir(parents=True, exist_ok=True)
    _ = cache.write_text(json.dumps({**key, "note": note}))
    return note
