"""Detecting drift in Claude Code's own env block.

The env-block field templates survive in the installed binary's string table
as plain literals. Reading the installed binary rather than a decompiled dump
is what makes the check track upgrades on its own: the dump is regenerated by
hand, the binary changes underfoot.

The check sees labels only. A change to how cc computes a value without
changing its label will not trip it, which is why the manifest pins the cc
version alongside the literals.

Two anchors, because the binary gives one string two jobs it stopped doing
at once. ANCHOR identifies the binary: a file containing cc's env-block
opening sentence is cc and not the wrapper script PATH resolves to.
WINDOW_ANCHOR locates the fields: the window is scanned around it, not
around ANCHOR. They were the same string through 2.1.235, where the bundler
happened to lay the opening sentence down beside the field templates. In
2.1.269 it does not -- the sentence and the templates are ~420 KB apart in
the same string-table region -- so a window on ANCHOR sees markdown-parser
regexes and HTTP/2 error strings and not one env field. The field templates
still cluster with each other, because one function (`AWr`,
chunk-dbb93264.js:29195) emits all of them, so the first of those templates
is the durable place to stand; the opening sentence's adjacency to them was
only ever a bundler coincidence.
"""

from __future__ import annotations

import hashlib
import json
import mmap
import os
import re
import shutil
import subprocess
import tempfile
from collections.abc import Callable, Mapping
from dataclasses import dataclass, field
from pathlib import Path
from typing import TypedDict, cast

ANCHOR = b"You have been invoked in the following environment: "
WINDOW_ANCHOR = b"Primary working directory: "
WINDOW_BEFORE = 1000
WINDOW_AFTER = 1000
PRINTABLE = re.compile(rb"[\x20-\x7e]{12,}")


class ManifestData(TypedDict):
    """The pinned-manifest shape `compare()` reads.

    basedpyright cannot check value types coming from json.loads, which are
    Any regardless of this declaration -- see `Facts` in render.py for the
    same caveat. The win here is the key set: a typo'd or renamed manifest
    key fails at the subscript instead of silently reading as Any everywhere
    downstream.
    """

    version: str
    window_literals: list[str]
    required_literals: dict[str, int]


class CacheEntry(TypedDict):
    """The on-disk shape of the drift cache file `cached_note()` reads back."""

    binary: str
    size: int
    mtime_ns: int
    manifest_sha: str
    note: str | None


@dataclass
class Comparison:
    matches: bool
    installed_version: str
    pinned_version: str
    added: list[str] = field(default_factory=list)
    removed: list[str] = field(default_factory=list)
    count_changes: dict[str, tuple[int, int]] = field(default_factory=dict)


def find_binary(env: Mapping[str, str] | None = None) -> Path:
    """Locate the running Claude Code binary.

    CLAUDE_CODE_EXECPATH is set in hook and tool subprocess environments and
    names the binary directly. The PATH fallback lands on a wrapper script
    under Nix, whose sibling `.claude-wrapped` symlink points at the real
    one. All three branches resolve through realpath, so one physical
    binary always keys the cache under the same string regardless of which
    branch found it.
    """
    env = os.environ if env is None else env
    execpath = env.get("CLAUDE_CODE_EXECPATH")
    if execpath and Path(execpath).is_file():
        return Path(os.path.realpath(execpath))

    found = shutil.which("claude", path=env.get("PATH"))
    if not found:
        if execpath:
            message = (
                f"claude is not on PATH and CLAUDE_CODE_EXECPATH={execpath!r} "
                "does not name a file"
            )
            raise RuntimeError(message)
        raise RuntimeError("claude is not on PATH and CLAUDE_CODE_EXECPATH is unset")
    real = Path(os.path.realpath(found))
    if _has_anchor(real):
        return real
    wrapped = real.parent / ".claude-wrapped"
    if wrapped.exists():
        return Path(os.path.realpath(wrapped))
    raise RuntimeError(
        f"{real} carries no env-block anchor and has no .claude-wrapped sibling"
    )


def _has_anchor(path: Path) -> bool:
    """Whether `path` contains ANCHOR, without reading the whole file.

    PATH's `claude` is normally a small wrapper script, but on a non-Nix
    install it can be the ~220 MB binary itself; mmap lets this check avoid
    loading that into memory before the cache (consulted afterwards, in
    `compare()`) even gets a say. mmap refuses a zero-length file, so an
    empty file is treated as anchor-less directly rather than raising.
    """
    with path.open("rb") as fh:
        if os.fstat(fh.fileno()).st_size == 0:
            return False
        with mmap.mmap(fh.fileno(), 0, access=mmap.ACCESS_READ) as mm:
            return mm.find(ANCHOR) != -1


def literals_in(data: bytes, source: str) -> list[str]:
    """Printable strings around the env block's first field template.

    WINDOW_ANCHOR rather than ANCHOR, and +/-1000 rather than the -3000/+1500
    those two constants carried while they were one anchor: at the field
    cluster the useful span is short, and widening it only pulls in the
    neighbouring output-style, language and HTTP/2 strings, which churn on
    releases that leave the env block alone. 1000 each way covers every
    field template `AWr` emits plus the model lines that follow them.
    """
    index = data.find(WINDOW_ANCHOR)
    if index < 0:
        raise RuntimeError(
            f"env-block field anchor {WINDOW_ANCHOR.decode()!r} not found in {source}"
        )
    start = max(0, index - WINDOW_BEFORE)
    window = data[start : index + WINDOW_AFTER]
    # A match that runs into either edge is a literal the window cut in half,
    # not a literal: `lastIngressUuidBySession` pins as `essUuidBySession`.
    # Half a string is still a string the comparison can diff, which is the
    # problem -- it moves whenever anything near the boundary shifts, so it
    # reports drift for releases that never touched the env block. Dropping
    # it costs one watched neighbour and buys a set that only moves when
    # something inside the window does.
    #
    # `finditer` rather than `findall` because deciding this needs each
    # match's span. Match[bytes].group() is typed to return the full match
    # for group 0, and PRINTABLE has no capture groups, so no cast is needed
    # here the way `findall`'s `list[Any]` return once required one.
    literals = {
        match.group().decode()
        for match in PRINTABLE.finditer(window)
        if match.start() > 0 and match.end() < len(window)
    }
    return sorted(literals)


def extract_literals(binary: Path) -> list[str]:
    return literals_in(binary.read_bytes(), str(binary))


def installed_version(binary: Path) -> str:
    """The version reported by the exact binary `compare()` will scan.

    Takes the resolved binary rather than resolving `claude` from PATH
    itself, so a PATH/CLAUDE_CODE_EXECPATH divergence cannot compare one
    binary's content against a different binary's version string -- the
    version participates in `matches`, and the result is cached keyed on
    this same binary. `timeout=10` bounds the one subprocess call Task 7's
    `except Exception` cannot absorb: that clause converts a raise into a
    note, but not a hang.

    The budget this shares with the SessionStart hook's own 30 s timeout
    (settings.json) and environment._git's 2 s (called up to five times per run):
    measured cold -- binary dropped from page cache, as happens on the
    first session after every Claude Code upgrade -- `claude --version`
    took 3.365 s and a from-disk compare() (the read plus the
    required_literals count passes) took 0.75 s; both comfortably clear
    their old, tighter caps (the version call's old 2 s cap, in particular,
    is why this number moved). Worst case, every capped call spends its
    full budget rather than actually finishing: 5x2 s git + 10 s version +
    ~2 s for a slower-than-measured cold read/scan + ~1 s of uncapped misc
    work (platform/shell/os_version, scratchpad mkdir, cache stat, JSON
    parsing) totals roughly 23 s against the 30 s outer timeout --
    `environment._executable`'s `--version` probe sits in that misc second:
    it runs only where the access check already failed, a nonexistent path
    fails to spawn instead of waiting, and a real shell answers at once, so
    the measured addition is 2 ms and only a path that exists and then hangs
    can spend its 1 s cap --
    comfortably inside it, not matching it, so cc's SIGTERM
    lands after this function would already have raised on its own, not
    instead of it. If any of these three numbers moves again, re-check this
    sum; see docs/superpowers/specs/2026-09-02-env-context-design.md's
    "Timeout budget" section for the fuller writeup.
    """
    try:
        result = subprocess.run(
            [str(binary), "--version"], capture_output=True, text=True, timeout=10
        )
    except subprocess.TimeoutExpired as exc:
        raise RuntimeError(f"{binary} --version timed out") from exc
    if result.returncode != 0:
        raise RuntimeError(f"{binary} --version failed: {result.stderr.strip()}")
    parts = result.stdout.split()
    if not parts:
        raise RuntimeError(f"{binary} --version produced no output")
    return parts[0]


def compare(binary: Path, manifest: Path, version: str) -> Comparison:
    """Diff the installed binary against the pinned manifest.

    The binary is ~220 MB (331 MB at 2.1.235), so it is read once and both
    checks run over the same bytes. `window_literals` catches fields cc adds near the anchor.
    `required_literals` catches a rename or removal of templates the
    window cannot see: two under its 12-character floor, and one carrying a
    non-ASCII character, which the string table holds as UTF-16 where the
    ASCII-only regex misses it even inside the window.
    These are compared by occurrence count rather than presence, because the
    strings also occur elsewhere in the binary — a rename scoped to cc's env
    builders leaves them present while dropping the total. See
    `notes/env-context-manifest.md`.
    """
    try:
        pinned = cast(ManifestData, json.loads(manifest.read_text()))
        window_literals = pinned["window_literals"]
        required_literals = pinned["required_literals"]
        pinned_version = pinned["version"]
    except (ValueError, OSError, KeyError) as exc:
        raise RuntimeError(f"failed to read manifest {manifest}: {exc}") from exc

    data = binary.read_bytes()
    found = set(literals_in(data, str(binary)))
    expected = set(window_literals)
    added = sorted(found - expected)
    removed = sorted(expected - found)
    changed = {
        literal: (pinned_count, count)
        for literal, pinned_count in required_literals.items()
        if (count := data.count(literal.encode())) != pinned_count
    }
    return Comparison(
        matches=(
            not added
            and not removed
            and not changed
            and version == pinned_version
        ),
        installed_version=version,
        pinned_version=pinned_version,
        added=added,
        removed=removed,
        count_changes=changed,
    )


def repin(binary: Path, manifest: Path, version: str) -> None:
    """Rewrite `manifest` to match `binary`, after `compare()` has shown a diff.

    Reads `binary` once here, independently of whatever `compare()` already
    read to produce the diff the caller showed before deciding to re-pin --
    the two calls this costs `--update` are accepted in exchange for this
    being one self-contained, independently testable read-and-rewrite
    rather than logic split between drift.py and a caller's own
    re-implementation, which is what previously lived inline in
    check-env-context.sh's heredoc.

    Refuses to write a required_literals count of zero. `compare()`'s
    count-changed check only fires on a change from the *pinned* count, so
    a literal re-pinned at 0 can never fail it again -- 0 is a floor, not
    a value a future occurrence can accidentally return to, which makes it
    a permanently-passing assertion masquerading as a live one. Reaching
    zero is exactly the rename or removal required_literals exists to
    catch; whether cc still needs this field watched at all -- and if so,
    under what new literal -- is a decision for render.py, not one a
    re-pin should make silently.
    """
    data = binary.read_bytes()
    pinned = cast(ManifestData, json.loads(manifest.read_text()))
    counts = {
        literal: data.count(literal.encode()) for literal in pinned["required_literals"]
    }
    zeroed = sorted(literal for literal, count in counts.items() if count == 0)
    if zeroed:
        names = ", ".join(repr(literal) for literal in zeroed)
        raise RuntimeError(
            f"{names} no longer appear anywhere in {binary} -- looks gone "
            "from cc entirely rather than merely renamed. Whether to keep "
            "watching this field, and under what literal, is a decision "
            "for src/claude_config/env_context/render.py; --update will "
            "not silently re-pin it at a count of 0."
        )
    pinned["version"] = version
    pinned["window_literals"] = literals_in(data, str(binary))
    pinned["required_literals"] = counts
    manifest.write_text(json.dumps(pinned, indent=2) + "\n")


def cached_note(
    binary: Path,
    manifest: Path,
    cache: Path,
    version: Callable[[], str] | None = None,
) -> str | None:
    """Return a one-line drift note, or None when the field set still matches.

    The result is cached on the binary's path, size, and mtime, plus a hash
    of the manifest's content, so the full scan runs once per Claude Code
    upgrade -- or once per manifest re-pin -- rather than once per session.
    The manifest is hashed rather than keyed on its mtime because Task 7
    points every worktree at one global cache: this repo alone has five
    worktrees, each with its own manifest file and its own mtime, so an
    mtime key thrashed to a full rescan on every alternation between
    checkouts even when their manifests were byte-identical copies of each
    other. The hash still catches a genuine re-pin
    (`check-env-context.sh --update`), and it also catches a same-mtime
    copy (`cp -p`, `rsync --times`) that an mtime key would miss --
    strictly stronger, for a ~2 KB file, free.

    A cache file that is unreadable, undecodable, or not a JSON object --
    a truncated write, invalid UTF-8, or valid JSON of the wrong shape, most
    plausibly from two sessions racing to write it at once -- is treated as
    a miss rather than raised: the scan reruns and `_write_cache` below
    overwrites the file, so the damage self-heals on the next session
    instead of wedging every session after it.
    """
    binary_stat = binary.stat()
    key = {
        "binary": str(binary),
        "size": binary_stat.st_size,
        "mtime_ns": binary_stat.st_mtime_ns,
        "manifest_sha": hashlib.sha256(manifest.read_bytes()).hexdigest(),
    }

    if cache.is_file():
        stored: object | None
        try:
            stored = cast(object, json.loads(cache.read_text()))
        except (ValueError, OSError):
            stored = None
        if isinstance(stored, dict):
            entry = cast(CacheEntry, cast(object, stored))
            if all(entry.get(k) == v for k, v in key.items()):
                return entry.get("note")

    resolved_version = version() if version is not None else installed_version(binary)
    result = compare(binary, manifest, resolved_version)
    note = None
    if not result.matches:
        # manifest lives at <repo root>/docs/env-context-manifest.json, so
        # its grandparent recovers the root without drift.py needing to know
        # about ROOT itself -- the note names an absolute script path the
        # agent can actually run, not a repo-relative one with no repo named.
        script = manifest.parent.parent / "scripts" / "check-env-context.sh"
        note = (
            f"Claude Code's env-block field set has drifted from the "
            f"{result.pinned_version} baseline this hook is pinned to "
            f"(installed version: {result.installed_version}); worth "
            f"mentioning to the user, who can run {script} to review."
        )
    _write_cache(cache, json.dumps({**key, "note": note}))
    return note


def _write_cache(cache: Path, payload: str) -> None:
    """Best-effort atomic write: a failure here means the answer goes
    unremembered, not that the check itself failed -- the caller's note is
    still correct even when this can't persist it. A directory sitting at
    the cache path, a read-only filesystem, or a full disk must cost one
    cache miss, not wedge every session after it the way an unguarded write
    would.

    tmp-file-plus-replace also removes the race outright rather than
    leaving the read side to tolerate it: with one global cache shared
    across every worktree (see this function's docstring), two sessions
    writing at once is the expected case, not the edge case, and a plain
    write_text call is exactly what produces the torn file the read guard
    exists to survive.
    """
    try:
        cache.parent.mkdir(parents=True, exist_ok=True)
        fd, tmp_name = tempfile.mkstemp(dir=cache.parent, prefix=f"{cache.name}.")
    except OSError:
        return
    try:
        with os.fdopen(fd, "w") as fh:
            _ = fh.write(payload)
        os.replace(tmp_name, cache)
    except OSError:
        try:
            Path(tmp_name).unlink(missing_ok=True)
        except OSError:
            pass
