#!/usr/bin/env bash
# Report when Claude Code's own env block drifts from the field set
# env-context is pinned to.
#
# Reads the installed binary's string table rather than the decompiled dump in
# /repos/claude-code-decompiled: the dump is regenerated by hand, the binary
# changes underfoot, and only the binary tracks an upgrade on its own.
#
# --update rewrites the manifest after you have reviewed a difference.
#
# Exit codes: 0 the field set matches (or --update re-pinned it); 1 the
# field set is stale and no --update was given; 2 a bad argument; 3 the
# check itself could not run -- no installed binary found, or --update
# refused to re-pin (see drift.repin's docstring for why).
set -euo pipefail
root="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")/.." && pwd)"
manifest="$root/docs/env-context-manifest.json"

update=0
while [ $# -gt 0 ]; do
	case "$1" in
	--update) update=1 ;;
	*)
		echo "check-env-context.sh: unknown argument: $1" >&2
		exit 2
		;;
	esac
	shift
done

cd "$root"
uv run --project "$root" python - "$manifest" "$update" <<'PY'
import json
import sys
from pathlib import Path

from claude_config.env_context import drift

manifest = Path(sys.argv[1])
update = sys.argv[2] == "1"

try:
    binary = drift.find_binary()
    version = drift.installed_version(binary)
    result = drift.compare(binary, manifest, version)
except RuntimeError as exc:
    print(f"check-env-context.sh: {exc}", file=sys.stderr)
    sys.exit(3)

pinned = json.loads(manifest.read_text())
print(f"binary:    {binary}")
print(f"pinned:    {result.pinned_version} ({len(pinned['window_literals'])} window literals)")
print(f"installed: {result.installed_version}")

if result.matches:
    print("OK: env-context field set matches the installed binary")
    sys.exit(0)

for literal in result.added:
    print(f"  + {literal!r}")
for literal in result.removed:
    print(f"  - {literal!r}")
for literal, (was, now) in result.count_changes.items():
    print(f"  ~ {literal!r} occurs {now} times, was {was}")

if update:
    try:
        drift.repin(binary, manifest, version)
    except RuntimeError as exc:
        print(f"check-env-context.sh: {exc}", file=sys.stderr)
        sys.exit(3)
    print(f"updated {manifest}")
    sys.exit(0)

print()
print("FAIL: env-context field set is stale.")
print("Review src/claude_config/env_context/render.py against the change, then")
print("re-run with --update to re-pin.")
sys.exit(1)
PY
