#!/usr/bin/env python3
"""Claude Code ntfy notification hook.

Sends push notifications via ntfy.sh when Claude Code needs attention
(permission prompts, idle, questions) or finishes a task. Invoked from
Claude Code's hooks system via `agent-tools ntfy-hook ...`.

Notifications include contextual 1-line summaries generated by an LLM
(OpenRouter / claude-haiku) from the conversation transcript.

Usage:
    python3 -m claude_config.ntfy_hook --action notify --type permission
    python3 -m claude_config.ntfy_hook --action stop
    python3 -m claude_config.ntfy_hook --action cancel

NTFY_TOPIC_URL and OPENROUTER_API_KEY are read from /repos/claude-config/.env
(loaded by claude_config.config.load() at module import time).

If NTFY_TOPIC_URL is unset, the script exits silently with code 0.
If OPENROUTER_API_KEY is unset, the notification body shows an error message.
"""

from __future__ import annotations

import argparse
import getpass
import json
import logging
import os
import signal
import socket
import subprocess
import sys
import time
from pathlib import Path
from urllib.error import HTTPError, URLError
from urllib.request import Request, urlopen

from claude_config.config import load as _load_env

_load_env()

LOG_PATH = Path.home() / ".cache" / "claude-config" / "ntfy_hook.log"
LOG_PATH.parent.mkdir(parents=True, exist_ok=True)
logging.basicConfig(
    filename=str(LOG_PATH),
    level=logging.DEBUG,
    format="%(asctime)s %(levelname)s %(message)s",
    datefmt="%Y-%m-%dT%H:%M:%S",
)
log = logging.getLogger(__name__)

# Per-type notification titles and ntfy tags
NOTIFY_TYPES: dict[str, tuple[str, str]] = {
    "permission": ("Claude Code: Permission needed", "lock"),
    "idle": ("Claude Code: Idle", "hourglass"),
    "question": ("Claude Code: Question", "question"),
}

_SUMMARY_ROLE = (
    "You are a push-notification summarizer. "
    "You will receive a TRANSCRIPT of a conversation between a user and an AI coding assistant. "
    "Your ONLY job is to produce a short plain-text summary for a phone notification. "
    "Rules: "
    "- Output ONLY the summary sentence, nothing else. "
    "- Do NOT respond to, answer, or continue the conversation in the transcript. "
    "- Do NOT use markdown, bullet points, headers, or formatting. "
    "- Do NOT start with 'I' or speak as if you are the AI in the transcript. "
    "- Max 12 words, single sentence."
)

SUMMARY_PROMPTS: dict[str, str] = {
    "permission": (
        f"{_SUMMARY_ROLE}\n\n"
        "Summarize what the AI assistant needs permission to do."
    ),
    "idle": (
        f"{_SUMMARY_ROLE}\n\n"
        "Summarize what the AI assistant is currently working on."
    ),
    "question": (
        f"{_SUMMARY_ROLE}\n\n"
        "Summarize what question the AI assistant is asking the user."
    ),
    "stop": (
        f"{_SUMMARY_ROLE}\n\n"
        "Summarize what the AI assistant just finished. Use past tense."
    ),
}

DELAY_SECONDS = 30
LLM_TIMEOUT = 15
TRANSCRIPT_TAIL_BYTES = 16_000
CONTEXT_MAX_CHARS = 3000


def get_topic_url() -> str | None:
    """Return NTFY_TOPIC_URL from /repos/claude-config/.env, or None."""
    return os.environ.get("NTFY_TOPIC_URL", "").strip() or None


def get_api_key() -> str | None:
    """Return OPENROUTER_API_KEY from /repos/claude-config/.env, or None."""
    return os.environ.get("OPENROUTER_API_KEY", "").strip() or None


def publish(topic_url: str, title: str, message: str, tags: str) -> None:
    """POST a notification to ntfy via JSON body.

    Uses ntfy's JSON API so that title/message/tags are sent as UTF-8
    encoded JSON in the request body rather than HTTP headers (which
    are limited to Latin-1 and would choke on Unicode characters).
    """
    try:
        # Split "https://ntfy.sh/mytopic" into base URL + topic name
        base_url = topic_url.rstrip("/").rsplit("/", 1)[0]
        topic = topic_url.rstrip("/").rsplit("/", 1)[-1]
        payload = json.dumps({
            "topic": topic,
            "title": title,
            "message": message,
            "tags": [tags],
        }).encode()
        req = Request(
            base_url,
            data=payload,
            headers={"Content-Type": "application/json"},
            method="POST",
        )
        urlopen(req, timeout=10)
        log.info("published to %s: title=%r body=%r", base_url, title, message[:200])
    except Exception as exc:
        log.error("publish failed: %s", exc)


def pidfile_path(session_id: str) -> Path:
    return Path(f"/tmp/claude-ntfy-{session_id}.pid")


def donefile_path(session_id: str) -> Path:
    return Path(f"/tmp/claude-ntfy-{session_id}.done")


def kill_pending(session_id: str) -> None:
    """Kill a pending delayed notification process, if any."""
    pf = pidfile_path(session_id)
    try:
        pid = int(pf.read_text().strip())
        os.kill(pid, signal.SIGTERM)
    except (FileNotFoundError, ValueError, ProcessLookupError, PermissionError):
        pass
    try:
        pf.unlink()
    except FileNotFoundError:
        pass


def read_hook_input() -> dict:
    """Read full JSON from stdin."""
    try:
        raw = sys.stdin.read()
        data = json.loads(raw)
        log.debug("hook input: %s", json.dumps({k: (v if k != "transcript_path" else v) for k, v in data.items()}, default=str)[:1000])
        return data
    except (json.JSONDecodeError, OSError) as exc:
        log.warning("failed to read hook input: %s", exc)
        return {}


# ---------------------------------------------------------------------------
# Transcript parsing & LLM summarization
# ---------------------------------------------------------------------------


def read_transcript_tail(path: str, max_bytes: int = TRANSCRIPT_TAIL_BYTES) -> list[str]:
    """Read the last *max_bytes* of a transcript file, returning whole lines.

    Seeks to end-minus-max_bytes so we never load the full file (transcripts
    can be tens of MB).  The first partial line is discarded.
    """
    p = Path(path)
    size = p.stat().st_size  # raises FileNotFoundError / OSError
    with p.open("r", encoding="utf-8", errors="replace") as f:
        if size > max_bytes:
            f.seek(size - max_bytes)
            f.readline()  # discard first partial line
        return f.readlines()


def extract_context(lines: list[str]) -> str:
    """Parse JSONL transcript lines into a compact conversation summary."""
    parts: list[str] = []
    total = 0
    parsed = 0
    skipped_types: dict[str, int] = {}

    for line in lines:
        if total >= CONTEXT_MAX_CHARS:
            break
        try:
            entry = json.loads(line)
        except (json.JSONDecodeError, TypeError):
            continue
        parsed += 1

        entry_type = entry.get("type", "?")
        if entry_type not in ("user", "assistant"):
            skipped_types[entry_type] = skipped_types.get(entry_type, 0) + 1
            continue

        message = entry.get("message", {})
        role = message.get("role", "")
        content = message.get("content", "")

        if role == "user":
            text = _extract_user_text(content)
            if text:
                part = f"User: {text[:500]}"
                parts.append(part)
                total += len(part)

        elif role == "assistant" and isinstance(content, list):
            for block in content:
                if total >= CONTEXT_MAX_CHARS:
                    break
                if not isinstance(block, dict):
                    continue
                part = _extract_assistant_block(block)
                if part:
                    parts.append(part)
                    total += len(part)

    combined = "\n".join(parts)
    log.debug(
        "extract_context: %d lines, %d parsed, %d parts, %d chars, skipped types: %s",
        len(lines), parsed, len(parts), len(combined), skipped_types,
    )
    return combined[-CONTEXT_MAX_CHARS:]


def _extract_user_text(content) -> str:
    """Extract readable text from a user message content field."""
    if isinstance(content, str):
        return content.strip()
    if isinstance(content, list):
        texts: list[str] = []
        for block in content:
            if not isinstance(block, dict):
                continue
            if block.get("type") == "text":
                texts.append(block.get("text", ""))
            elif block.get("type") == "tool_result":
                body = block.get("content", "")
                if isinstance(body, str) and body:
                    texts.append(f"[tool result: {body[:100]}]")
        return " ".join(texts).strip()
    return ""


def _extract_assistant_block(block: dict) -> str | None:
    """Extract a single readable part from an assistant content block."""
    btype = block.get("type")
    if btype == "text":
        text = block.get("text", "").strip()
        if text:
            return f"Assistant: {text[:500]}"
    elif btype == "tool_use":
        name = block.get("name", "?")
        inp = block.get("input", {})
        if name == "Bash" and "command" in inp:
            detail = inp["command"][:200]
        elif name in ("Read", "Write", "Edit", "Glob", "Grep"):
            detail = (inp.get("file_path") or inp.get("pattern") or "")[:200]
        else:
            detail = str(inp)[:100]
        return f"Tool: {name}({detail})"
    return None


def generate_summary(api_key: str, context: str, hook_type: str) -> str:
    """Call OpenRouter claude-haiku for a 1-line summary."""
    prompt = SUMMARY_PROMPTS.get(hook_type, SUMMARY_PROMPTS["idle"])
    # Wrap transcript so the model treats it as data, not a live conversation
    user_msg = (
        "--- BEGIN TRANSCRIPT ---\n"
        f"{context}\n"
        "--- END TRANSCRIPT ---\n\n"
        "Write the notification summary:"
    )
    payload = json.dumps({
        "model": "anthropic/claude-haiku-4.5",
        "messages": [
            {"role": "system", "content": prompt},
            {"role": "user", "content": user_msg},
        ],
        "max_tokens": 80,
        "temperature": 0,
    }).encode()

    req = Request(
        "https://openrouter.ai/api/v1/chat/completions",
        data=payload,
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        },
        method="POST",
    )

    try:
        resp_bytes = urlopen(req, timeout=LLM_TIMEOUT).read()
    except HTTPError as exc:
        body = ""
        try:
            body = exc.read().decode("utf-8", errors="replace")[:100]
        except Exception:
            pass
        raise RuntimeError(f"OpenRouter {exc.code}: {body}") from exc
    except URLError as exc:
        if "timed out" in str(exc.reason).lower():
            raise RuntimeError(f"OpenRouter timeout ({LLM_TIMEOUT}s)") from exc
        raise RuntimeError(f"OpenRouter error: {exc.reason}") from exc

    try:
        data = json.loads(resp_bytes)
        return data["choices"][0]["message"]["content"].strip()
    except (json.JSONDecodeError, KeyError, IndexError, TypeError) as exc:
        raise RuntimeError(f"Bad OpenRouter response: {exc}") from exc


def _format_location(cwd: str) -> str:
    """Return a compact 'user@host:path' location string."""
    try:
        user = getpass.getuser()
    except Exception:
        user = "?"
    try:
        host = socket.gethostname().split(".")[0]  # short hostname
    except Exception:
        host = "?"
    prefix = f"{user}@{host}"
    if cwd:
        # Show last 2 path components for brevity: "repos/claude-config"
        parts = Path(cwd).parts
        short = str(Path(*parts[-2:])) if len(parts) >= 2 else cwd
        return f"{prefix}:{short}"
    return prefix


def was_interrupted(transcript_path: str) -> bool:
    """Heuristic: check if the agent turn ended due to interruption (e.g. Ctrl+C).

    Returns True if the last assistant message has pending tool_use calls
    without corresponding tool_result responses, suggesting the user
    interrupted the agent mid-task.
    """
    if not transcript_path:
        return False
    try:
        lines = read_transcript_tail(transcript_path, max_bytes=8000)
    except (FileNotFoundError, OSError):
        return False

    entries = []
    for line in lines:
        try:
            entries.append(json.loads(line))
        except (json.JSONDecodeError, TypeError):
            continue

    if not entries:
        return False

    # Walk backward: find the last assistant entry
    last_assistant_idx = None
    for i in range(len(entries) - 1, -1, -1):
        if entries[i].get("type") == "assistant":
            last_assistant_idx = i
            break

    if last_assistant_idx is None:
        return False

    content = entries[last_assistant_idx].get("message", {}).get("content", [])
    if not isinstance(content, list):
        return False

    has_tool_use = any(
        isinstance(b, dict) and b.get("type") == "tool_use"
        for b in content
    )
    if not has_tool_use:
        return False

    # Check if any subsequent entry contains tool_result
    for entry in entries[last_assistant_idx + 1 :]:
        user_content = entry.get("message", {}).get("content", [])
        if isinstance(user_content, list) and any(
            isinstance(b, dict) and b.get("type") == "tool_result"
            for b in user_content
        ):
            return False  # tool results found → not interrupted

    # tool_use without tool_result → likely interrupted
    return True


def is_mid_turn_stop(transcript_path: str) -> bool:
    """Return True if this Stop event is from a mid-turn subagent completion.

    When the main agent finishes, the last assistant entry is a text response
    (no tool_use). When a subagent finishes mid-turn, the last assistant entry
    dispatched tools, tool results came back, but no new assistant text follows.
    """
    if not transcript_path:
        return False
    try:
        lines = read_transcript_tail(transcript_path, max_bytes=8000)
    except (FileNotFoundError, OSError):
        return False

    entries = []
    for line in lines:
        try:
            entries.append(json.loads(line))
        except (json.JSONDecodeError, TypeError):
            continue

    if not entries:
        return False

    # Find the last assistant entry
    last_assistant_idx = None
    for i in range(len(entries) - 1, -1, -1):
        if entries[i].get("type") == "assistant":
            last_assistant_idx = i
            break

    if last_assistant_idx is None:
        return False

    content = entries[last_assistant_idx].get("message", {}).get("content", [])
    if not isinstance(content, list):
        return False

    has_agent_tool = any(
        isinstance(b, dict) and b.get("type") == "tool_use" and b.get("name") == "Agent"
        for b in content
    )
    if not has_agent_tool:
        return False  # No Agent dispatch → not a mid-turn subagent stop

    # Tool_use exists — check if tool_results came back but agent hasn't
    # produced a new response yet (mid-turn subagent completion).
    has_tool_result = False
    for entry in entries[last_assistant_idx + 1:]:
        if entry.get("type") == "assistant":
            return False  # Agent continued after tools — this is a normal stop
        if entry.get("type") == "user":
            user_content = entry.get("message", {}).get("content", [])
            if isinstance(user_content, list) and any(
                isinstance(b, dict) and b.get("type") == "tool_result"
                for b in user_content
            ):
                has_tool_result = True

    return has_tool_result


def last_pending_tool(transcript_path: str) -> str | None:
    """Return the name of the last pending tool_use (no tool_result yet), or None."""
    try:
        lines = read_transcript_tail(transcript_path, max_bytes=8000)
    except (FileNotFoundError, OSError):
        return None

    entries = []
    for line in lines:
        try:
            entries.append(json.loads(line))
        except (json.JSONDecodeError, TypeError):
            continue

    # Walk backward to find the last assistant entry
    for i in range(len(entries) - 1, -1, -1):
        if entries[i].get("type") != "assistant":
            continue
        content = entries[i].get("message", {}).get("content", [])
        if not isinstance(content, list):
            continue
        # Find the last tool_use block in this assistant message
        tool_name = None
        for block in content:
            if isinstance(block, dict) and block.get("type") == "tool_use":
                tool_name = block.get("name")
        if tool_name:
            return tool_name
        break  # only check the last assistant entry

    return None


def build_notification(transcript_path: str | None, hook_type: str, cwd: str = "") -> str:
    """Orchestrate summary generation. Returns body text or [err] message.

    All results (success or error) include a location suffix line.
    """
    log.debug("build_notification: path=%r type=%r cwd=%r", transcript_path, hook_type, cwd)
    location = _format_location(cwd)

    api_key = get_api_key()
    if not api_key:
        return f"[err] No API key (set OPENROUTER_API_KEY in /repos/claude-config/.env)\n{location}"

    if not transcript_path:
        log.warning("no transcript_path in hook input")
        return f"[err] No transcript_path in hook input\n{location}"

    try:
        lines = read_transcript_tail(transcript_path)
        log.debug("read %d lines from transcript (%s)", len(lines), transcript_path)
    except FileNotFoundError:
        log.warning("transcript not found: %s", transcript_path)
        return f"[err] Transcript not found: {transcript_path}\n{location}"
    except OSError as exc:
        log.warning("transcript read error: %s", exc)
        return f"[err] Transcript read error: {exc}\n{location}"

    context = extract_context(lines)
    if not context.strip():
        # Early in session — no conversation yet, send without summary
        return location

    try:
        summary = generate_summary(api_key, context, hook_type)
        return f"{summary}\n{location}"
    except RuntimeError as exc:
        return f"[err] {exc}\n{location}"


# ---------------------------------------------------------------------------
# Action handlers
# ---------------------------------------------------------------------------


def do_notify(args: argparse.Namespace) -> None:
    if args.delayed:
        # Re-invoked child: sleep, build summary, publish, clean up
        time.sleep(DELAY_SECONDS)
        if donefile_path(args.session_id).exists():
            pass
        elif (topic_url := get_topic_url()):
            body = build_notification(args.transcript_path, args.hook_type or args.type or "idle", args.cwd)
            publish(topic_url, args.message_title, body, args.message_tag)
        try:
            pidfile_path(args.session_id).unlink()
        except FileNotFoundError:
            pass
        return

    # Parent: read stdin, kill pending, spawn delayed child
    hook_input = read_hook_input()
    session_id = hook_input.get("session_id", "unknown")
    kill_pending(session_id)

    if donefile_path(session_id).exists():
        return

    topic_url = get_topic_url()
    if not topic_url:
        return

    transcript_path = hook_input.get("transcript_path", "")

    # Derive type from stdin JSON (notification_type) or CLI --type flag
    raw_type = hook_input.get("notification_type", "") or args.type or ""
    # Map Claude Code notification_type values to our internal types
    _TYPE_MAP = {
        "permission_prompt": "permission",
        "idle_prompt": "idle",
        "elicitation_dialog": "question",
    }
    notify_type = _TYPE_MAP.get(raw_type, raw_type) if raw_type else "idle"
    if notify_type not in NOTIFY_TYPES:
        notify_type = "idle"
    # AskUserQuestion fires notification_type=idle_prompt (older Claude Code
    # versions used permission_prompt). Detect via pending tool and relabel
    # so the notification reads "Question" instead of "Idle" / "Permission".
    if notify_type in ("permission", "idle") and transcript_path:
        pending = last_pending_tool(transcript_path)
        if pending == "AskUserQuestion":
            log.debug("reclassified %s -> question (pending tool: AskUserQuestion)", notify_type)
            notify_type = "question"
    title, tag = NOTIFY_TYPES.get(notify_type, NOTIFY_TYPES["idle"])
    cwd = hook_input.get("cwd", "")
    project = Path(cwd).name if cwd else ""
    if project:
        title = f"{title} ({project})"

    child = subprocess.Popen(
        [
            sys.executable,
            "-m", "claude_config.ntfy_hook",
            "--action", "notify",
            "--delayed",
            "--session-id", session_id,
            "--message-title", title,
            "--message-tag", tag,
            "--transcript-path", transcript_path,
            "--hook-type", notify_type,
            "--cwd", cwd,
        ],
        start_new_session=True,
        stdin=subprocess.DEVNULL,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )

    pidfile_path(session_id).write_text(str(child.pid))


def do_stop(args: argparse.Namespace) -> None:
    if args.delayed:
        # Re-invoked child: build summary and publish immediately
        if (topic_url := get_topic_url()):
            body = build_notification(args.transcript_path, "stop", args.cwd)
            publish(topic_url, args.message_title, body, args.message_tag)
        return

    # Parent: read stdin, kill pending, touch donefile, spawn async child
    hook_input = read_hook_input()
    session_id = hook_input.get("session_id", "unknown")
    kill_pending(session_id)

    # Already sent a "Done" for this session — don't spam.
    if donefile_path(session_id).exists():
        log.debug("suppressed stop notification: donefile exists (session %s)", session_id)
        return

    transcript_path = hook_input.get("transcript_path", "")

    # Skip "done" notification if the agent was interrupted (e.g. Ctrl+C)
    if was_interrupted(transcript_path):
        log.debug("suppressed stop notification: interrupted (session %s)", session_id)
        return

    # Skip mid-turn subagent completions (tool dispatched, result back,
    # but agent hasn't produced its next response yet).
    if is_mid_turn_stop(transcript_path):
        log.debug("suppressed stop notification: mid-turn subagent stop (session %s)", session_id)
        return

    # Create donefile only after confirming this is a real stop,
    # so mid-turn suppression doesn't block subsequent idle notifications.
    donefile_path(session_id).touch()

    topic_url = get_topic_url()
    if not topic_url:
        return
    cwd = hook_input.get("cwd", "")
    title = "Claude Code: Done"
    project = Path(cwd).name if cwd else ""
    if project:
        title = f"{title} ({project})"

    subprocess.Popen(
        [
            sys.executable,
            "-m", "claude_config.ntfy_hook",
            "--action", "stop",
            "--delayed",
            "--session-id", session_id,
            "--message-title", title,
            "--message-tag", "white_check_mark",
            "--transcript-path", transcript_path,
            "--hook-type", "stop",
            "--cwd", cwd,
        ],
        start_new_session=True,
        stdin=subprocess.DEVNULL,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )


def do_cancel(_args: argparse.Namespace) -> None:
    hook_input = read_hook_input()
    session_id = hook_input.get("session_id", "unknown")
    kill_pending(session_id)
    # Task-notifications (background task completions) are system-generated,
    # not real user re-engagement. Keep the donefile so do_stop doesn't
    # re-fire "Done" for each stale background task.
    prompt = hook_input.get("prompt", "")
    if prompt.lstrip().startswith("<task-notification>"):
        log.debug("cancel: keeping donefile for task-notification (session %s)", session_id)
        return
    try:
        donefile_path(session_id).unlink()
    except FileNotFoundError:
        pass


def main() -> None:
    parser = argparse.ArgumentParser(description="Claude Code ntfy notification hook")
    parser.add_argument(
        "--action",
        required=True,
        choices=["notify", "stop", "cancel"],
    )
    parser.add_argument(
        "--type",
        choices=["permission", "idle", "question"],
        help="Notification type (for --action notify)",
    )

    # Internal flags for delayed re-invocation
    parser.add_argument("--delayed", action="store_true", help=argparse.SUPPRESS)
    parser.add_argument("--session-id", help=argparse.SUPPRESS)
    parser.add_argument("--message-title", help=argparse.SUPPRESS)
    parser.add_argument("--message-tag", default="bell", help=argparse.SUPPRESS)
    parser.add_argument("--transcript-path", help=argparse.SUPPRESS)
    parser.add_argument("--hook-type", help=argparse.SUPPRESS)
    parser.add_argument("--cwd", default="", help=argparse.SUPPRESS)

    args = parser.parse_args()

    handlers = {
        "notify": do_notify,
        "stop": do_stop,
        "cancel": do_cancel,
    }
    handlers[args.action](args)


if __name__ == "__main__":
    main()
